### PR TITLE
macstadium: separate worker pool for free jobs on com staging

### PR DESCRIPTION
**Pull request by igorwwwwwwwwwwwwwwwwwwww**
As part of the merge, we are wanting to have a separate worker pool for free jobs running on travis-ci.com. This is so that if there is a backlog, paying customers will be isolated. The plan is then to gradually adjust the pool sizes, essentially shifting capacity from `org` to `com-staging`, as we migrate more users over to com.

This is a first step, which creates a new `com-free` worker pool, which consumes from the `builds.macstadium6-free` queue in RabbitMQ. It is otherwise identical to the `com` pool.

refs https://github.com/travis-ci/reliability/issues/118

### CODE REVIEW

**Comment by Halle** [comment]
Hi Igor,

I'd like to go over this plan generally on Monday if that's OK, will send call invite.

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
Main points from our conversation:

* This patch is a proposal, I'd love to get feedback and am happy to consider other approaches
* If possible, Team Mac should own the rollout, capacity allocation, and capacity shifting for this, especially as we move to production

**Comment by Lyoness** [comment]
>Team Mac should own the rollout, capacity allocation, and capacity shifting for this, especially as we move to production


@igorwwwwwwwwwwwwwwwwwwww, after assessing this, this change is ok to apply, *however*,  after discussion with @Halle and @mjm, the knowledge & understanding of how to assess capacity allocation and shifting has sadly not been documented...yet  I'd like solve that immediately by putting this into documentation in the builder's manual today/tomorrow morning so that any member of the infra-mac team can look at PR like this and be able to approve. 

_Tis' been too long that this yonder tribal knowledge not been shared to the mighty manual_ 💟  ☠️

**Comment by Lyoness** [comment]
_Thar it blows_: https://github.com/travis-pro/manual/pull/844

**Comment by Halle** [comment]
LGTM!

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
This was applied, I manually started the workers:

```
igor@wjb-1:~$ sudo start travis-worker-staging-com-free-1
travis-worker-staging-com-free-1 start/running, process 1111
igor@wjb-1:~$ sudo start travis-worker-staging-com-free-2
travis-worker-staging-com-free-2 start/running, process 1132
```

The `builds.macstadium6-free` queue showed up in rabbit, so I'd say this is working!

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
(pod-2 has not been applied yet, pending review of the slightly larger diff)

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
Applied on pod-2 now as well!

**Pull request merged**
